# Rust workflow

name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Archive target dir
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: target
    - name: Cache cargo packages
      uses: actions/cache@v3
      with:
        key: pkgs
        path: ~/.cargo/registry
      
